language: android
android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.1
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-22

  notifications:
    slack: iot-2016:UXyDg9Ii7NjIVTdVIwX9CIJP