language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - android-25
  - build-tools-25.0.1
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  before_install:
  - chmod +x gradlew
  notifications:
    email: false
    secure: S0CMpsrHj0cLf1LOqzonr/lbBw4arvKvKLwq1EAePiuMkGpk4KdyRVGCGSU0LFrCOPRFXNU+mZ75vfu8rWyfOzTzYMKxVlNZ2DQZwrk9Xabg1Q/p890d6cmjsBOXUfeEw/FWXedInYuplxEtpXQW+bB0t7e1REWwwjGtk/E5UfzfHXfVM2ynW1/oytoNY6+k7NsIR0whBzeW+POrW+u99LyVU7wB6VHTtE/Lx3dSGqqGy21g8vN+ZxacTFQ7EQg94l40kb9Z50j67EM9/YHwCnGkcBspe+/cMT/3Cptplpiz0W0wCK5AQ1n9UJYLGckAosop3cfDQLEfeVHQ3v5N+L1fru2gl9gMtb1NysllXw0BXRcxlX3ftCFljMu/NSBVq2+0M4rAjduVIjI2ORh9ukY/bIawEzp0Ln8SqpyCe2VuOzlCSmUGeKqC8M5NN4hQuWDjvApOiaWwHEAFGNsg2dD0ReumXXpxkRSoo3h1nZijFRtatCmablFI5AmR8f5dnvP517uyDid/Xm+ljTRkvuCY807wWimziUwXI9FpVtxwdM0g584/5rdpPi+9v86jFyKp8qYzeH/rhAwWZ9DrOPe2zvF/EITUUq/cnP1mW5VBuh7/W0qi16GSaq2rdzHrKKq6MuCAqmBxxHHMB47p4By5TzNiF73c9OPTRE6tAzU=
    on_success: always
    on_failure: always
    on_start: false