language: android
android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.1
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-22

  notifications:
    email: false
    slack: iot-2016:UXyDg9Ii7NjIVTdVIwX9CIJP
    on_success: always
    on_failure: always

  before_install:
    - chmod +x gradlew